### ISSUE TITLE
Local HTML File Error

### ISSUE THREAD

**Issue by Violat0r** [TeamUlysses/ulx#16]
Using the latest ulx with a local HTML file causes the following error. I replaced the motd.txt with a file that contains HTML.

[ERROR] addons/ulx-master/lua/ulx/modules/cl/motdmenu.lua:216: attempt to index field 'motdSettings' (a nil value)
  1. generateMotdHTML - addons/ulx-master/lua/ulx/modules/cl/motdmenu.lua:216
   2. fn - addons/ulx-master/lua/ulx/modules/cl/motdmenu.lua:30
    3. func - addons/ulib-master-1_12_2016/lua/ulib/client/cl_util.lua:22
     4. unknown - lua/includes/extensions/net.lua:32

**Comment by SticklyMan** [comment]
Due to workshop restrictions (and potential security concerns about having motd stored in the data folder), we moved away from loading the MOTD from a local file and replaced it with an MOTD generator. The generator can create/configure a quick MOTD without having to know any HTML.

However, we are planning on bringing back support for a local HTML file- it's probably used more likely than we think. We are working out the details and will have something soon.

For now, you'll either have to stick with the MOTD generator, or find a place you host your webpage and access it via URL.

**Comment by Nayruden** [comment]
This bug (ULX not recognizing malformed MOTD setting files) has not been fixed yet, but you *can* use MOTD files again with ea5840ab5b77251cda26972ac900604148ce6540

**Comment by Violat0r** [comment]
The newest changed to ulx broke the url option. It does not save the url and reverts back to ulyssesmod.net.

**Comment by Nayruden** [comment]
Delete your ULX config file under data/ and see if the problem persists.

**Comment by SticklyMan** [comment]
We've just changed the cvars to to ulx_motdfile and ulx_motdurl, and adjusted the configurations. This should solve the issues with the URL not saving.
