### ISSUE TITLE
Ulx Group Rights Auto Reset.

### ISSUE THREAD

**Issue by JaanusDex** [TeamUlysses/ulx#44]
### Steps to reproduce
1. I have configure all rights all Groups..
2. Restart All my Work Restet.
3. All back to Creating the Groups.

### Expected behavior
Today i have configure all rights for all groups, 2 Hours later daily restart on my server after the restart im joining my server and all rights back to the default rights and all groups that i create are there but not configure.

### Actual behavior
I can now right for 5 times to adjust all rights for all groups.

### Error(s) in server console, if any

No Errors

### Error(s) in player's console, if any

No Errors

### Version
ULib v2.60d
ULX v3.70d

**Comment by Nayruden** [comment]
@JaanusDex, we've had several people report similar problems in the past, but it's almost always due to one of the following:

1. Permissions on the server are setup incorrectly. The server needs read/write access to everything in the data directory.
2. Conflicts with other scripts. DarkRP/FAdmin has historically been the worst offender for poorly programmed hooks and checks.

Hopefully, this gives you a base to figure out what's going on. Another option would be to use the users.txt in the settings directory to make yourself an admin, which would be loaded on each load and cannot be modified by Lua scripts.

**Comment by JaanusDex** [comment]
okay Thank you.
