### ISSUE TITLE
My ULX Menu Does Not Work

### ISSUE THREAD

**Issue by HarveyBatchelor** [TeamUlysses/ulx#72]
### Steps to reproduce
1. ?
2. ?
3. ?
### Expected behavior

When I type Menu In Chat It Should Open The ULX menu And Show Me All My Commands Ect
### Actual behavior

It opens and Its completly blank and doesnt work
### Error(s) in server console, if any

None
### Error(s) in player's console, if any

[ERROR] lua/vgui/dcategorycollapse.lua:33: attempt to index field 'Category' (a nil value)
1. UpdateColours - lua/vgui/dcategorycollapse.lua:33
   1. ApplySchemeSettings - lua/vgui/dlabel.lua:78
   2. unknown - lua/vgui/dcategorycollapse.lua:272
### Version

ULib v2.60
ULX v3.70
![20160829213219_1](https://cloud.githubusercontent.com/assets/21319954/18066498/98dafc18-6e30-11e6-9e89-4a63e0da324b.jpg)

**Comment by Nayruden** [comment]
@SticklyMan, I'm turning to you for this one

**Comment by SticklyMan** [comment]
Errors like this are typically caused by Derma skins or conflicting addons. Go to your CLIENT's garrysmod/data/ulx/xgui.txt file and change the "skin" line to "Default", or just remove the xgui.txt file entirely and rejoin.

If that does not work, try running your server with JUST ulx/ulib enabled, and see if the error still occurs.

**Comment by Nayruden** [comment]
Assuming issue is fixed, given lack of response.
